import type { AuditAction } from '../models';

export const AUDIT_ACTION_LABELS: Record<AuditAction, string> = {
  'user.created': 'User created',
  'user.updated': 'User updated',
  'user.disabled': 'User disabled',
  'user.enabled': 'User enabled',
  'club.created': 'Club created',
  'club.updated': 'Club updated',
  'club.deleted': 'Club deleted',
  'group.created': 'Group created',
  'group.updated': 'Group updated',
  'group.deleted': 'Group deleted',
  'group.member_added': 'Member added to group',
  'group.member_removed': 'Member removed from group',
  'group.member_transferred': 'Member transferred',
  'session.created': 'Session created',
  'session.updated': 'Session updated',
  'session.cancelled': 'Session cancelled',
  'attendance.marked': 'Attendance marked',
  'attendance.batch_submitted': 'Attendance batch submitted',
  'medal.template_created': 'Medal template created',
  'medal.awarded': 'Medal awarded',
  'medal.transferred': 'Medal transferred',
  'goal.created': 'Goal created',
  'goal.updated': 'Goal updated',
  'goal.completed': 'Goal completed',
  'invite.created': 'Invite created',
  'invite.claimed': 'Invite claimed',
};

export const AUDIT_ACTION_SEVERITY: Record<AuditAction, 'info' | 'warning' | 'critical'> = {
  'user.created': 'info',
  'user.updated': 'info',
  'user.disabled': 'warning',
  'user.enabled': 'info',
  'club.created': 'info',
  'club.updated': 'info',
  'club.deleted': 'critical',
  'group.created': 'info',
  'group.updated': 'info',
  'group.deleted': 'warning',
  'group.member_added': 'info',
  'group.member_removed': 'warning',
  'group.member_transferred': 'info',
  'session.created': 'info',
  'session.updated': 'info',
  'session.cancelled': 'warning',
  'attendance.marked': 'info',
  'attendance.batch_submitted': 'info',
  'medal.template_created': 'info',
  'medal.awarded': 'info',
  'medal.transferred': 'info',
  'goal.created': 'info',
  'goal.updated': 'info',
  'goal.completed': 'info',
  'invite.created': 'info',
  'invite.claimed': 'info',
};
