import type { NotificationType } from '../models';

export const NOTIFICATION_TITLES: Record<NotificationType, string> = {
  session_reminder: 'Upcoming Session',
  session_cancelled: 'Session Cancelled',
  session_scheduled: 'New Session Scheduled',
  attendance_marked: 'Attendance Updated',
  medal_awarded: 'Medal Awarded!',
  goal_progress: 'Goal Progress',
  goal_completed: 'Goal Completed!',
  achievement_earned: 'Achievement Unlocked!',
  group_joined: 'Joined Group',
  group_left: 'Left Group',
  level_up: 'Level Up!',
  invite_received: 'Invitation Received',
  member_joined: 'New Member',
  member_left: 'Member Left',
  system: 'System Notice',
};

export const NOTIFICATION_ICONS: Record<NotificationType, string> = {
  session_reminder: 'calendar',
  session_cancelled: 'calendar-x',
  session_scheduled: 'calendar-plus',
  attendance_marked: 'check-circle',
  medal_awarded: 'medal',
  goal_progress: 'target',
  goal_completed: 'trophy',
  achievement_earned: 'star',
  group_joined: 'users',
  group_left: 'users',
  level_up: 'arrow-up',
  invite_received: 'mail',
  member_joined: 'user-plus',
  member_left: 'user-minus',
  system: 'info',
};

export const NOTIFICATION_COLORS: Record<NotificationType, string> = {
  session_reminder: 'blue',
  session_cancelled: 'red',
  session_scheduled: 'blue',
  attendance_marked: 'green',
  medal_awarded: 'yellow',
  goal_progress: 'cyan',
  goal_completed: 'green',
  achievement_earned: 'violet',
  group_joined: 'teal',
  group_left: 'orange',
  level_up: 'green',
  invite_received: 'indigo',
  member_joined: 'teal',
  member_left: 'orange',
  system: 'gray',
};
